### ISSUE TITLE
npm build builds the demo instead of the library 

### ISSUE THREAD

**Issue by skounis** [DevUnltd/js-library-boilerplate#1667]
Hi @hodgef 

Really great job! 

I noticed however that the `npm run build` builds the `demo/index.js` instead of the `lib/index.js`. As a result  `window.MyLibrary` is not available when we load the `build/index.js` library with a `<script>` tag.
 
It look that the problem is solved when we replace `'src/demo/index')` with  `'src/lib/index'),` in 

https://github.com/DevUnltd/js-library-boilerplate/blob/75549a81a6b07e5dc3c1369deaa70e6e95330b0f/config/paths.js#L54

**Comment by hodgef** [comment]
Thanks @skounis ! This should be fixed now
