### ISSUE TITLE
Use with Typescript

### ISSUE THREAD

**Issue by markhats** [DevUnltd/js-library-boilerplate#1701]
Hello

I have an existing create-react-app application that I'm looking to convert to a library. The app is mainly Typescript but also contains a small amount of js. Is it possible to use this boilerplate to convert my app? If so, what changes do I need to make to allow it to work with Typescript?

Thanks.

**Comment by hodgef** [comment]
I recommend using the following boilerplate to create TS libraries:
https://github.com/DevUnltd/ts-library-boilerplate-basic

If not, you'd have to create a typescript app with create-react-app, eject, then compare it with what you have right now:
https://create-react-app.dev/docs/adding-typescript/

Regards,
Francisco Hodge
